CREATE TABLE INVOICES(
  ID INT PRIMARY KEY,
  NUMBER VARCHAR(50) UNIQUE NOT NULL,
  PURCHAER_ID INT
);

CREATE TABLE INVOICES_POSITIONS(
  ID INT PRIMARY KEY,
  INVOICE_ID INT NOT NULL,
  COMMODITY VARCHAR(100) NOT NULL,
  QUANTITY INT NOT NULL DEFAULT(1),
  SINGLE_NET_PRICE DECIMAL NOT NULL,
  VAT_CATEGORY INT,
  FOREIGN KEY (INVOICE_ID) REFERENCES INVOICES(ID)
);

CREATE TABLE PURCHASERS(
  ID INT PRIMARY KEY,
  NAME VARCHAR(100) UNIQUE NOT NULL,
  ADDRESS VARCHAR(200),
  TAX_IDENTIFIER VARCHAR(10)
);

